version: "3"
services:
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: news_postgres
      POSTGRES_USER: netdb
      POSTGRES_PASSWORD: netdb2602
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pipenv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
