version: "3"
services:
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - sample.env
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pipenv run uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
